# Generated by Django 2.2 on 2020-11-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('carts', '0002_auto_20201125_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='products',
        ),
        migrations.AddField(
            model_name='cart_item',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='product.Products'),
        ),
    ]
