# Generated by Django 2.2 on 2020-12-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('carts', '0004_auto_20201125_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='products',
        ),
        migrations.AddField(
            model_name='cart_item',
            name='products',
            field=models.ManyToManyField(blank=True, to='product.Products'),
        ),
    ]
