# Generated by Django 2.2.16 on 2020-12-23 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_comment_reply_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply_comment',
            old_name='comment',
            new_name='comment_id',
        ),
        migrations.RenameField(
            model_name='reply_comment',
            old_name='user_reply',
            new_name='user_reply_id',
        ),
    ]
