# Generated by Django 2.2 on 2020-11-24 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('total_cost', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_num', models.CharField(max_length=12)),
                ('email_Address', models.CharField(max_length=100)),
                ('home_Address', models.CharField(max_length=200)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(max_length=100)),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('payment_method', models.CharField(max_length=50, null=True)),
                ('total_cost', models.BigIntegerField(null=True)),
                ('delivery', models.BigIntegerField(null=True)),
                ('price', models.BigIntegerField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('adress', models.CharField(max_length=100, null=True)),
                ('product_name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=100, null=True)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toped.customer')),
                ('payment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toped.payment')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=1000)),
                ('rate', models.IntegerField(null=True)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toped.customer')),
                ('products_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Products')),
            ],
        ),
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('cart_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toped.cart')),
                ('payment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toped.payment')),
            ],
        ),
        migrations.CreateModel(
            name='cart_item',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('img_product', models.ImageField(default='', upload_to='static/img')),
                ('price', models.BigIntegerField(null=True)),
                ('Quantity', models.IntegerField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toped.customer')),
                ('products_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Products')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toped.cart_item'),
        ),
    ]
