# Generated by Django 2.2 on 2020-11-24 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toped', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='cart_item',
            name='products_id',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='cart_id',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='products_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_id',
        ),
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.DeleteModel(
            name='cart_item',
        ),
        migrations.DeleteModel(
            name='checkout',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
        migrations.DeleteModel(
            name='payment',
        ),
        migrations.DeleteModel(
            name='rating',
        ),
        migrations.DeleteModel(
            name='transaction',
        ),
    ]
