# Generated by Django 2.2 on 2020-12-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('toped', '0002_auto_20201124_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=50)),
                ('payment_id', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('payment_method', models.CharField(max_length=50, null=True)),
                ('total_cost', models.BigIntegerField(null=True)),
                ('delivery', models.BigIntegerField(null=True)),
                ('price', models.BigIntegerField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('adress', models.CharField(max_length=100, null=True)),
                ('product_name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
